### PR TITLE
Implemented Mobilepay

### PR DESCRIPTION
**Pull request by aait**

### CODE REVIEW

**Comment by asbjornu** [comment]
I still find it strange that this is not dependent on SwedbankPay/swedbank-pay-sdk-php#15.

**Comment by aait** [comment]
> I still find it strange that this is not dependent on [SwedbankPay/swedbank-pay-sdk-php#15](https://github.com/SwedbankPay/swedbank-pay-sdk-php/pull/15).

That was updated. It depends on that now

**Review by asbjornu — APPROVED** [review]
Would it be possible to have some tests for this repository?

**Comment by aait** [comment]
> Would it be possible to have some tests for this repository?

This repository already has tests of MobilePay

**Pull request merged**
